# Generated by Django 6.0.7 on 2026-08-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='is_dish_available',
            new_name='is_available',
        ),
    ]
