# Generated by Django 6.0.7 on 2026-08-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_is_dish_available_menu_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='customer',
        ),
    ]
