# Generated by Django 6.0.7 on 2026-08-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menu_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
