# Generated by Django 6.0.7 on 2026-08-14 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.PositiveIntegerField(default=1)),
                ('number_of_guests', models.PositiveBigIntegerField(default=1)),
                ('table_name', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('OPEN', 'Open'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('special_request', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
