# Generated by Django 6.0.7 on 2026-08-07 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('RESERVED', 'reserved'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=20)),
                ('table_number', models.PositiveIntegerField(default=1)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('special_request', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
