# Generated by Django 6.0.7 on 2026-08-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_is_open_to_is_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
